theme: jekyll-theme-minimal
lang: es-UY
title: Brisa.uy
description: Relatos de navegación
author: Brisa
logo: assets/images/brisa_logo_600.png
license: Licencia Creative Commons
  Atribución-NoComercial-CompartirIgual 4.0 Internacional

plugins:
 - jekyll-feed
 - jekyll-seo-tag
 - jekyll-paginate

paginate: 7

header_pages:
 - index.html
 - sobre.md
 - conecta.md
