theme: jekyll-theme-minimal
lang: es-UY
title: Brisa.uy
description: Aventuras del velero Brisa navegando rumbo a Uruguay
author: Douglas Lovell
logo: assets/images/brisa_logo_600.png
license: Licencia Creative Commons
  Atribución-NoComercial-CompartirIgual 4.0 Internacional

plugins:
 - jekyll-feed
 - jekyll-seo-tag

header_pages:
 - artículos.md
 - sobre.md
 - inicio.md
